# Site settings
title: Razi Shaban
email: rrshaban at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Swarthmore 2016 CS/Linguistics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.razi.xyz" # the base hostname & protocol for your site
twitter_username: razishaban
github_username:  rrshaban

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  # - jekyll-font-awesome